framework:
    messenger:
#        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    use_notify: true
#                    check_delayed_interval: 60000
#                retry_strategy:
#                    max_retries: 3
#                    multiplier: 2
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            fanout:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order.fanout
                        type: fanout
                    queues:
                        order1.fanout:
                        order2.fanout:

            direct:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: sms.direct
                        type: direct
                    queues:
                        sms.service1:
                            binding_keys: [ 'sms1' ]
                        sms.service2:
                            binding_keys: [ 'sms2' ]

        routing:
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            # Symfony\Component\Notifier\Message\ChatMessage: async
            # Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Message\Command\CreateOrder': fanout
            'App\Message\Command\SignUpSms': direct